version: '3'

tasks:
  web:deps:
    cmds:
      - pnpm config set store-dir ~/workspaces/airbnb/web/pnpm
      - cd web && pnpm install --force
  web:dev:
    cmds:
      - cd web && npm run dev
  web:start:
    cmds:
      - cd web && npm run start
  web:build:
    cmds:
      - cd web && npm run build
  web:preview:
    cmds:
      - cd web && npm run preview
  web:astro:
    cmds:
      - cd web && npm run astro