version: '3'

tasks:
  web:deps:
    cmds:
      - pnpm config set store-dir ~/workspaces/airbnb/web/pnpm
      - cd web && pnpm install
  web:dev:
    cmds:
      - cd web && pnpm run dev
  web:start:
    cmds:
      - cd web && pnpm run start
  web:build:
    cmds:
      - cd web && pnpm run build
  web:preview:
    cmds:
      - cd web && pnpm run preview
  web:astro:
    cmds:
      - cd web && pnpm run astro
